import { ArtboardPreset, TypeboxState } from "./types";

export const ARTBOARD_PRESETS: ArtboardPreset[] = [
  // SNS Presets
  { id: "1:1", label: "1:1 Square", category: "sns", width: 1080, height: 1080 },
  { id: "16:9", label: "16:9 Landscape", category: "sns", width: 1920, height: 1080 },
  { id: "4:5", label: "4:5 Portrait", category: "sns", width: 1080, height: 1350 },
  { id: "9:16", label: "9:16 Story/Reel", category: "sns", width: 1080, height: 1920 },

  // Poster & Print Presets
  { id: "A4", label: "A4", category: "print", width: 1240, height: 1754 },
  { id: "A4-L", label: "A4 Landscape", category: "print", width: 1754, height: 1240 },
  { id: "A3", label: "A3", category: "print", width: 1754, height: 2480 },
  { id: "A5", label: "A5", category: "print", width: 874, height: 1240 },
  { id: "2:3", label: "2:3 Poster", category: "print", width: 1200, height: 1800 },
];

export const DEFAULT_TYPEBOX_STATE: TypeboxState = {
  sourceMode: "text",
  text: "TYPEBOX\nGRAPHIC",
  textAlign: "center",
  svgContent: null,
  svgFileName: null,
  svgScale: 1.0,

  fontFamily: "Pretendard",
  customFontName: null,
  customFontUrl: null,
  fontWeight: "700",
  fontSize: 96,
  letterSpacing: 0,
  lineHeight: 1.15,

  transform: {
    x: 0,
    y: 0,
    rotate: 0,
    perspectiveV: 0,
    perspectiveH: 0,
  },

  color: {
    textColor: "#111113",
    bgColor: "#F6F6F3",
    transparent: false,
  },

  activeEffect: "type",

  dither: {
    shape: "dot",
    cellSize: 13,
    dotSize: 0.85,
    angle: 65,
  },

  line: {
    thickness: 6,
    gap: 8,
    angle: 45,
    offset: 0,
    seed: 1,
  },

  slice: {
    pieces: 12,
    offset: 24,
    mode: "alternate",
    seed: 1,
  },

  boom: {
    origin: "center",
    shape: "dot",
    shardSize: 14,
    spread: 60,
    shardSvgContent: null,
    shardSvgName: null,
    seed: 1,
  },

  crack: {
    pieces: 24,
    gap: 4,
    scatter: 12,
    spread: 20,
    seed: 1,
  },

  artboardWidth: 1080,
  artboardHeight: 1080,
  exportScale: 2,
  language: "en",
};

export const TRANSLATIONS = {
  en: {
    title: "TODOTOOL — Typebox",
    subtitle: "Text & Vector Graphic Effect Generator",
    back: "Back",
    source: "SOURCE",
    tabText: "Text",
    tabSvg: "SVG File",
    loadSvg: "Load SVG",
    svgHint: "Illustrator (.ai) is not directly supported — export to SVG first. Shapes merge into a silhouette.",
    font: "FONT",
    fontFamily: "Font",
    customFont: "My Font",
    loadFont: "Load Font (.ttf/.otf/.woff)",
    weight: "Weight",
    size: "Size",
    letterSpacing: "Letter Spacing",
    lineHeight: "Line Height",
    transform: "POSITION · TRANSFORM",
    posX: "X",
    posY: "Y",
    rotate: "Rotate",
    perspectiveV: "Perspective Vertical",
    perspectiveH: "Perspective Horizontal",
    resetAll: "Reset all",
    color: "COLOR",
    textColor: "Text",
    bgColor: "Background",
    transparent: "Transparent",
    effect: "EFFECT",
    typeEffect: "Type",
    ditherEffect: "Dither",
    lineEffect: "Line",
    sliceEffect: "Slice",
    boomEffect: "Boom",
    crackEffect: "Crack",
    // Dither
    shape: "Shape",
    dot: "Dot",
    square: "Square",
    triangle: "Triangle",
    cell: "Cell",
    dotSize: "Dot size",
    angle: "Angle",
    // Line
    thickness: "Thickness",
    gap: "Gap",
    offset: "Offset",
    shuffle: "Shuffle",
    // Slice
    pieces: "Pieces",
    mode: "Mode",
    alternate: "Alternate",
    random: "Random",
    // Boom
    origin: "Origin",
    perGlyph: "Per glyph",
    center: "Center",
    top: "Top",
    bottom: "Bottom",
    left: "Left",
    right: "Right",
    topLeft: "Top left",
    topRight: "Top right",
    bottomLeft: "Bottom left",
    bottomRight: "Bottom right",
    shardFile: "Shard file",
    shardSize: "Shard size",
    spread: "Spread",
    boomHint: "Load an SVG to use as shards (dots until loaded)",
    // Crack
    scatter: "Scatter",
    // Artboard
    artboard: "ARTBOARD",
    snsPresets: "SNS Presets",
    printPresets: "Poster · Print",
    width: "Width",
    height: "Height",
    // Export
    export: "EXPORT",
    pngScale: "PNG Scale",
    savePng: "Save PNG",
    saveSvg: "Save SVG",
    exportNote: "SVG export converts text to paths, so it opens as vectors anywhere — no fonts required.",
    preview: "LIVE PREVIEW",
    zoom: "Zoom",
    fit: "Fit",
  },
  ko: {
    title: "TODOTOOL — Typebox",
    subtitle: "텍스트 및 벡터 그래픽 이펙트 생성기",
    back: "돌아가기",
    source: "SOURCE (소스 선택)",
    tabText: "Text",
    tabSvg: "SVG File",
    loadSvg: "SVG 불러오기",
    svgHint: "Illustrator (.ai) 파일은 지원하지 않습니다. SVG로 내보낸 후 불러와주세요.",
    font: "FONT (서체)",
    fontFamily: "폰트",
    customFont: "My Font",
    loadFont: "폰트 로드 (.ttf/.otf/.woff)",
    weight: "굵기 (Weight)",
    size: "크기 (Size)",
    letterSpacing: "자간 (Letter Spacing)",
    lineHeight: "행간 (Line Height)",
    transform: "POSITION · TRANSFORM (변형)",
    posX: "X (가로)",
    posY: "Y (세로)",
    rotate: "Rotate (회전)",
    perspectiveV: "원근 상하 (Vertical)",
    perspectiveH: "원근 좌우 (Horizontal)",
    resetAll: "Reset all (초기화)",
    color: "COLOR (색상)",
    textColor: "글자 색상",
    bgColor: "배경 색상",
    transparent: "투명 (Transparent)",
    effect: "EFFECT (이펙트)",
    typeEffect: "Type (타입)",
    ditherEffect: "Dither (디더)",
    lineEffect: "Line (라인)",
    sliceEffect: "Slice (슬라이스)",
    boomEffect: "Boom (붐)",
    crackEffect: "Crack (크랙)",
    // Dither
    shape: "모양 (Shape)",
    dot: "원 (Dot)",
    square: "사각 (Square)",
    triangle: "삼각 (Triangle)",
    cell: "셀 크기 (Cell)",
    dotSize: "도트 크기 (Dot size)",
    angle: "각도 (Angle)",
    // Line
    thickness: "두께 (Thickness)",
    gap: "간격 (Gap)",
    offset: "오프셋 (Offset)",
    shuffle: "셔플 (Shuffle)",
    // Slice
    pieces: "조각 수 (Pieces)",
    mode: "모드 (Mode)",
    alternate: "교차 (Alternate)",
    random: "랜덤 (Random)",
    // Boom
    origin: "폭발 기준점 (Origin)",
    perGlyph: "글자별 (Per glyph)",
    center: "중앙 (Center)",
    top: "상단 (Top)",
    bottom: "하단 (Bottom)",
    left: "좌측 (Left)",
    right: "우측 (Right)",
    topLeft: "좌측 상단",
    topRight: "우측 상단",
    bottomLeft: "좌측 하단",
    bottomRight: "우측 하단",
    shardFile: "샤드 파일 (Shard file)",
    shardSize: "파편 크기 (Shard size)",
    spread: "확산 (Spread)",
    boomHint: "SVG를 로드하여 파편으로 사용하세요 (로드 전까지 점으로 표시).",
    // Crack
    scatter: "산란도 (Scatter)",
    // Artboard
    artboard: "ARTBOARD (아트보드)",
    snsPresets: "SNS 비율",
    printPresets: "포스터 · 인쇄 (Print)",
    width: "가로 (Width)",
    height: "세로 (Height)",
    // Export
    export: "EXPORT (내보내기)",
    pngScale: "PNG 해상도 배율",
    savePng: "Save PNG (PNG 저장)",
    saveSvg: "Save SVG (SVG 벡터 저장)",
    exportNote: "SVG로 내보내면 폰트가 없어도 벡터 패스로 안전하게 열립니다.",
    preview: "라이브 프리뷰",
    zoom: "배율",
    fit: "화면 맞춤",
  },
};
