'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Send } from 'lucide-react';

type Message = { _id: string; message: string; senderRole: string; createdAt: string };
type Ticket = { _id: string; ticketNumber: string; subject: string; status: string; priority: string; createdAt: string; categoryId?: { name?: string } };

export default function SupportTicketPage({ params }: { params: Promise<{ id: string }> }) {
  const [ticket, setTicket] = useState<Ticket | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [message, setMessage] = useState(''); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void params.then(({ id }) => fetch(`/api/support/tickets/${id}`).then((r) => r.json()).then((data) => { if (!data.success) throw new Error(data.error); setTicket(data.ticket); setMessages(data.messages || []); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Ticket not found.'))); }, [params]);
  const send = async () => { if (!ticket || message.trim().length < 5) return; setSending(true); try { const response = await fetch(`/api/support/tickets/${ticket._id}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to send message.'); setMessage(''); const refreshed = await fetch(`/api/support/tickets/${ticket._id}`).then((r) => r.json()); setTicket(refreshed.ticket); setMessages(refreshed.messages || []); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to send message.'); } finally { setSending(false); } };
  if (error) return <main className="mx-auto max-w-3xl px-4 py-12"><p className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-600 dark:text-red-300">{error}</p></main>;
  if (!ticket) return <main className="mx-auto max-w-3xl px-4 py-12 text-sm text-foreground/60">Loading ticket...</main>;
  return <main className="mx-auto grid w-full max-w-5xl gap-6 px-4 pb-20 pt-8 lg:grid-cols-[1fr_280px] sm:px-6"><section><Link href="/support" className="inline-flex items-center gap-2 text-xs font-bold text-foreground/60 hover:text-primary"><ArrowLeft className="h-4 w-4" /> Support Center</Link><header className="mt-7 border-b border-foreground/10 pb-5"><p className="text-xs font-bold text-primary">{ticket.ticketNumber}</p><h1 className="mt-1 text-2xl font-black">{ticket.subject}</h1><p className="mt-2 text-xs text-foreground/55">{ticket.categoryId?.name || 'Support'} · Created {new Date(ticket.createdAt).toLocaleString()}</p></header><div className="space-y-4 py-6">{messages.length === 0 ? <p className="text-sm text-foreground/55">Start the conversation with MCUSTOCK Support.</p> : messages.map((item) => <article key={item._id} className={`rounded-2xl border p-4 ${item.senderRole === 'user' ? 'border-primary/20 bg-primary/10' : 'border-foreground/10 bg-foreground/[0.04]'}`}><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold text-primary">{item.senderRole === 'user' ? 'You' : 'MCUSTOCK Support'}</span><time className="text-[10px] text-foreground/45">{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-foreground/80">{item.message}</p></article>)}</div><div className="rounded-2xl border border-foreground/10 bg-foreground/[0.03] p-4"><textarea value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="Write a message..." rows={4} className="w-full resize-none bg-transparent text-sm text-foreground outline-none" /><div className="flex justify-end border-t border-foreground/10 pt-3"><button onClick={() => void send()} disabled={sending || message.trim().length < 5} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs font-bold text-background disabled:opacity-50"><Send className="h-3.5 w-3.5" />{sending ? 'Sending...' : 'Send'}</button></div></div></section><aside className="h-fit rounded-2xl border border-foreground/10 bg-foreground/[0.03] p-5"><p className="text-xs font-bold uppercase tracking-wider text-foreground/50">Ticket information</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-xs text-foreground/50">Status</dt><dd className="mt-1 font-bold text-primary">{ticket.status.replaceAll('_', ' ')}</dd></div><div><dt className="text-xs text-foreground/50">Priority</dt><dd className="mt-1 font-bold">{ticket.priority}</dd></div></dl></aside></main>;
}
