import type { ChartTemplate, ChartType } from "./types";

export const chartCategories = [
  "All",
  "Favorites",
  "Candles",
  "Lines",
  "Area",
  "Bars",
  "Professional",
  "Crypto",
  "Neon",
  "Minimal",
  "Futures",
];

export const curatedTemplates: ChartTemplate[] = [
  {
    id: "binance-pro",
    name: "Binance Pro Dark",
    category: "Crypto",
    chartType: "candlestick",
    background: "#0b0e11",
    gridColor: "#1e2329",
    bullishColor: "#0ecb81",
    bearishColor: "#f6465d",
    lineColor: "#fcd535",
    volumeColor: "#0ecb81",
    textColor: "#eaecef",
    accentColor: "#fcd535",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.25,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "tradingview-midnight",
    name: "TradingView Midnight",
    category: "Professional",
    chartType: "candlestick",
    background: "#131722",
    gridColor: "#2a2e39",
    bullishColor: "#22ab94",
    bearishColor: "#f23645",
    lineColor: "#2962ff",
    volumeColor: "#22ab94",
    textColor: "#d1d4dc",
    accentColor: "#2962ff",
    candleWidth: 7,
    wickWidth: 1.5,
    gridOpacity: 0.2,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "bloomberg-terminal",
    name: "Bloomberg Terminal",
    category: "Professional",
    chartType: "ohlc",
    background: "#000000",
    gridColor: "#ff9900",
    bullishColor: "#ff9900",
    bearishColor: "#ff3333",
    lineColor: "#ff9900",
    volumeColor: "#ff9900",
    textColor: "#ff9900",
    accentColor: "#ff9900",
    candleWidth: 5,
    wickWidth: 1.5,
    gridOpacity: 0.18,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: false,
    glow: true,
    gradient: false,
    builtIn: true,
  },
  {
    id: "cyberpunk-neon",
    name: "Cyberpunk 2077",
    category: "Neon",
    chartType: "area",
    background: "#0f051d",
    gridColor: "#3b1464",
    bullishColor: "#00ffcc",
    bearishColor: "#ff007f",
    lineColor: "#00ffcc",
    volumeColor: "#00ffcc",
    textColor: "#e0b0ff",
    accentColor: "#ff007f",
    candleWidth: 6,
    wickWidth: 2,
    gridOpacity: 0.3,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: true,
    builtIn: true,
  },
  {
    id: "emerald-matrix",
    name: "Emerald Matrix",
    category: "Crypto",
    chartType: "candlestick",
    background: "#04130c",
    gridColor: "#0b3824",
    bullishColor: "#10b981",
    bearishColor: "#ef4444",
    lineColor: "#34d399",
    volumeColor: "#10b981",
    textColor: "#a7f3d0",
    accentColor: "#34d399",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.25,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: false,
    builtIn: true,
  },
  {
    id: "sunset-mountain",
    name: "Sunset Mountain",
    category: "Area",
    chartType: "mountain",
    background: "#1a0b1e",
    gridColor: "#45184f",
    bullishColor: "#f97316",
    bearishColor: "#ec4899",
    lineColor: "#fb923c",
    volumeColor: "#f97316",
    textColor: "#fed7aa",
    accentColor: "#f43f5e",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.22,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: false,
    glow: true,
    gradient: true,
    builtIn: true,
  },
  {
    id: "heikin-ashi-pro",
    name: "Heikin Trend Pro",
    category: "Candles",
    chartType: "heikin-ashi",
    background: "#0a1118",
    gridColor: "#1e2c3a",
    bullishColor: "#06b6d4",
    bearishColor: "#f43f5e",
    lineColor: "#38bdf8",
    volumeColor: "#06b6d4",
    textColor: "#e0f2fe",
    accentColor: "#38bdf8",
    candleWidth: 7,
    wickWidth: 2,
    gridOpacity: 0.2,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "electric-pulse-line",
    name: "Electric Pulse Line",
    category: "Lines",
    chartType: "line",
    background: "#050b14",
    gridColor: "#13233a",
    bullishColor: "#38bdf8",
    bearishColor: "#f87171",
    lineColor: "#38bdf8",
    volumeColor: "#38bdf8",
    textColor: "#bae6fd",
    accentColor: "#38bdf8",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.2,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: true,
    builtIn: true,
  },
  {
    id: "gold-futures-desk",
    name: "Gold Futures Desk",
    category: "Futures",
    chartType: "candlestick",
    background: "#14120c",
    gridColor: "#38311a",
    bullishColor: "#eab308",
    bearishColor: "#ef4444",
    lineColor: "#facc15",
    volumeColor: "#eab308",
    textColor: "#fef08a",
    accentColor: "#facc15",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.25,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: false,
    builtIn: true,
  },
  {
    id: "hollow-minimal-dark",
    name: "Hollow Clean Pro",
    category: "Candles",
    chartType: "hollow",
    background: "#0f172a",
    gridColor: "#1e293b",
    bullishColor: "#22c55e",
    bearishColor: "#ef4444",
    lineColor: "#3b82f6",
    volumeColor: "#22c55e",
    textColor: "#cbd5e1",
    accentColor: "#3b82f6",
    candleWidth: 7,
    wickWidth: 1.5,
    gridOpacity: 0.2,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "deep-ocean-area",
    name: "Deep Ocean Area",
    category: "Area",
    chartType: "area",
    background: "#031525",
    gridColor: "#0c3254",
    bullishColor: "#0284c7",
    bearishColor: "#f43f5e",
    lineColor: "#38bdf8",
    volumeColor: "#0284c7",
    textColor: "#e0f2fe",
    accentColor: "#38bdf8",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.22,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: true,
    builtIn: true,
  },
  {
    id: "clean-light-studio",
    name: "Clean Light Studio",
    category: "Minimal",
    chartType: "candlestick",
    background: "#f8fafc",
    gridColor: "#e2e8f0",
    bullishColor: "#16a34a",
    bearishColor: "#dc2626",
    lineColor: "#2563eb",
    volumeColor: "#16a34a",
    textColor: "#334155",
    accentColor: "#2563eb",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.6,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "baseline-zero-flow",
    name: "Baseline Zero Flow",
    category: "Lines",
    chartType: "baseline",
    background: "#090d16",
    gridColor: "#1a2332",
    bullishColor: "#10b981",
    bearishColor: "#f43f5e",
    lineColor: "#60a5fa",
    volumeColor: "#10b981",
    textColor: "#cbd5e1",
    accentColor: "#60a5fa",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.22,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: true,
    builtIn: true,
  },
  {
    id: "tokyo-violet-neon",
    name: "Tokyo Violet Neon",
    category: "Neon",
    chartType: "candlestick",
    background: "#120824",
    gridColor: "#2c1554",
    bullishColor: "#c084fc",
    bearishColor: "#fb7185",
    lineColor: "#a855f7",
    volumeColor: "#c084fc",
    textColor: "#f3e8ff",
    accentColor: "#c084fc",
    candleWidth: 7,
    wickWidth: 2,
    gridOpacity: 0.3,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: false,
    builtIn: true,
  },
  {
    id: "step-signal-matrix",
    name: "Step Signal Matrix",
    category: "Lines",
    chartType: "step",
    background: "#021208",
    gridColor: "#0a2f19",
    bullishColor: "#22c55e",
    bearishColor: "#ef4444",
    lineColor: "#4ade80",
    volumeColor: "#22c55e",
    textColor: "#bbf7d0",
    accentColor: "#4ade80",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.25,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: false,
    glow: true,
    gradient: false,
    builtIn: true,
  },
  {
    id: "financial-bars-pro",
    name: "Wall Street Tick Bars",
    category: "Bars",
    chartType: "bar",
    background: "#0e131f",
    gridColor: "#20293d",
    bullishColor: "#059669",
    bearishColor: "#e11d48",
    lineColor: "#3b82f6",
    volumeColor: "#059669",
    textColor: "#e2e8f0",
    accentColor: "#3b82f6",
    candleWidth: 6,
    wickWidth: 2,
    gridOpacity: 0.2,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "monochrome-slate",
    name: "Monochrome Slate",
    category: "Minimal",
    chartType: "candlestick",
    background: "#0f1115",
    gridColor: "#232730",
    bullishColor: "#ffffff",
    bearishColor: "#52525b",
    lineColor: "#a1a1aa",
    volumeColor: "#ffffff",
    textColor: "#e4e4e7",
    accentColor: "#ffffff",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.2,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: false,
    glow: false,
    gradient: false,
    builtIn: true,
  },
  {
    id: "aurora-borealis-area",
    name: "Aurora Borealis",
    category: "Area",
    chartType: "area",
    background: "#03141a",
    gridColor: "#0a3442",
    bullishColor: "#14b8a6",
    bearishColor: "#f43f5e",
    lineColor: "#2dd4bf",
    volumeColor: "#14b8a6",
    textColor: "#ccfbf1",
    accentColor: "#2dd4bf",
    candleWidth: 6,
    wickWidth: 1.5,
    gridOpacity: 0.25,
    fontSize: 11,
    showVolume: true,
    showGrid: true,
    showPriceScale: true,
    showTimeScale: true,
    showCrosshair: true,
    movingAverage: true,
    glow: true,
    gradient: true,
    builtIn: true,
  }
];

export const chartTemplates: ChartTemplate[] = curatedTemplates;
export const defaultTemplate = chartTemplates[0];
