"use client";

import { useEffect, useState } from 'react';
import { BarChart3, Coins, Database, ImageIcon, Layers3, Users, WandSparkles } from 'lucide-react';

type Analytics = { usage: { metadataGenerated: number; backgroundRemoved: number; threeDGenerated: number; apiRequests: number; creditsUsed: number; storageUsedMB: number }; newUsers: Array<{ _id: string; count: number }>; planDistribution: Array<{ _id: string; count: number }>; aiCost: Array<{ _id: string; estimatedCost: number; requests: number }>; plans: number; days: number };
const metrics = [['New users', 'newUsers', Users], ['Metadata', 'metadataGenerated', WandSparkles], ['Background removals', 'backgroundRemoved', ImageIcon], ['3D generations', 'threeDGenerated', Layers3], ['Credits used', 'creditsUsed', Coins], ['Storage (MB)', 'storageUsedMB', Database]] as const;

export default function AdminAnalyticsPage() {
  const [data, setData] = useState<Analytics | null>(null);
  const [days, setDays] = useState('30');
  const [error, setError] = useState('');
  useEffect(() => { fetch(`/api/admin/analytics?days=${days}`, { credentials: 'include' }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Unable to load analytics.'); setData(payload); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load analytics.')); }, [days]);
  const totalNewUsers = data?.newUsers.reduce((sum, item) => sum + item.count, 0) || 0;
  return <div className="mx-auto max-w-7xl space-y-7"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-primary">Performance</p><h2 className="mt-2 text-3xl font-black">Analytics</h2><p className="mt-2 text-sm text-white/55">Product activity and operating cost across the selected period.</p></div><select value={days} onChange={(event) => setDays(event.target.value)} className="rounded-xl border border-white/10 bg-white/[0.05] px-3 py-2 text-sm text-white outline-none focus:border-primary/60"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></section>{error && <div className="rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(([label, key, Icon]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 shadow-xl backdrop-blur-xl"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-white/50">{label}</p><Icon className="h-4 w-4 text-primary" /></div><p className="mt-5 text-3xl font-black">{data ? key === 'newUsers' ? totalNewUsers : data.usage[key as keyof Analytics['usage']] : '—'}</p></div>)}</section><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 shadow-xl backdrop-blur-xl"><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-primary" /><h3 className="font-black">Plan / role distribution</h3></div><div className="mt-5 space-y-3">{data?.planDistribution.map((item) => <div key={item._id} className="flex items-center justify-between border-b border-white/10 pb-3 text-sm"><span className="font-semibold text-white/70">{item._id || 'unassigned'}</span><span className="font-black text-primary">{item.count}</span></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 shadow-xl backdrop-blur-xl"><div className="flex items-center gap-2"><Coins className="h-4 w-4 text-primary" /><h3 className="font-black">AI cost by provider</h3></div><div className="mt-5 space-y-3">{data?.aiCost.length ? data.aiCost.map((item) => <div key={item._id} className="flex items-center justify-between border-b border-white/10 pb-3 text-sm"><span className="font-semibold text-white/70">{item._id}</span><span className="font-black text-primary">${item.estimatedCost.toFixed(2)}</span></div>) : <p className="text-sm text-white/45">No AI cost records in this period.</p>}</div></section></div><div className="rounded-2xl border border-primary/20 bg-primary/[0.06] p-5 text-sm text-white/65"><span className="font-bold text-primary">{data?.usage.apiRequests ?? 0}</span> API requests recorded. Active plans configured: <span className="font-bold text-primary">{data?.plans ?? 0}</span>.</div></div>;
}