import JSZip from 'jszip';
import { ProjectState, AnimationTrack } from './types';
import { computeElementStylesAtTime, applyComputedStylesToElement } from './animationEngine';
import { FFmpeg } from '@ffmpeg/ffmpeg';
import { fetchFile, toBlobURL } from '@ffmpeg/util';

export interface RecordedVideo {
  blob: Blob;
  format: 'mp4' | 'webm';
}

let ffmpegInstance: FFmpeg | null = null;
let ffmpegLoadPromise: Promise<FFmpeg> | null = null;

/**
 * 1. Generate Standalone Animated SVG with embedded CSS Keyframes
 */
export function generateAnimatedSvg(project: ProjectState): string {
  const { svgRaw, tracks, document: docSettings } = project;
  const { duration, loop } = docSettings;

  if (typeof window === 'undefined') return svgRaw;

  const parser = new DOMParser();
  const doc = parser.parseFromString(svgRaw, 'image/svg+xml');
  const svg = doc.querySelector('svg');
  if (!svg) return svgRaw;

  // Group tracks by elementId
  const tracksByElement = new Map<string, AnimationTrack[]>();
  for (const t of tracks) {
    if (!tracksByElement.has(t.elementId)) {
      tracksByElement.set(t.elementId, []);
    }
    tracksByElement.get(t.elementId)!.push(t);
  }

  let cssRules = `
    /* Generated by MCU SVG Motion Studio */
    svg { overflow: visible; }
  `;

  tracksByElement.forEach((elemTracks, elementId) => {
    const el = svg.querySelector(`[data-mcu-id="${elementId}"]`);
    if (!el) return;

    // Collect all unique timestamps
    const timestamps = new Set<number>([0, duration]);
    elemTracks.forEach((tr) => {
      tr.keyframes.forEach((kf) => timestamps.add(Math.max(0, Math.min(duration, kf.time))));
    });

    const sortedTimes = Array.from(timestamps).sort((a, b) => a - b);
    const keyframesName = `anim_${elementId.replace(/[^a-zA-Z0-9_]/g, '_')}`;

    let keyframesCss = `@keyframes ${keyframesName} {\n`;

    sortedTimes.forEach((t) => {
      const pct = Math.round((t / duration) * 1000) / 10;
      const styles = computeElementStylesAtTime(elemTracks, elementId, t);

      const transform = `translate(${styles.x}px, ${styles.y}px) rotate(${styles.rotation}deg) scale(${styles.scaleX / 100}, ${styles.scaleY / 100}) skewX(${styles.skewX}deg) skewY(${styles.skewY}deg)`;
      const opacity = Math.max(0, Math.min(1, styles.opacity / 100));

      keyframesCss += `  ${pct}% {\n`;
      keyframesCss += `    transform: ${transform};\n`;
      keyframesCss += `    transform-origin: ${styles.originX}% ${styles.originY}%;\n`;
      keyframesCss += `    opacity: ${opacity};\n`;
      if (styles.strokeDashoffset !== undefined) {
        keyframesCss += `    stroke-dashoffset: ${styles.strokeDashoffset};\n`;
      }
      keyframesCss += `  }\n`;
    });

    keyframesCss += `}\n`;

    cssRules += keyframesCss;
    cssRules += `
      [data-mcu-id="${elementId}"] {
        animation: ${keyframesName} ${duration}s ${loop ? 'infinite' : 'forwards'} linear;
        transform-box: fill-box;
      }\n`;
  });

  // Inject <style> into <defs> or <svg>
  let defs = svg.querySelector('defs');
  if (!defs) {
    defs = doc.createElementNS('http://www.w3.org/2000/svg', 'defs');
    svg.insertBefore(defs, svg.firstChild);
  }

  const styleEl = doc.createElementNS('http://www.w3.org/2000/svg', 'style');
  styleEl.setAttribute('type', 'text/css');
  styleEl.textContent = cssRules;
  defs.appendChild(styleEl);

  const serializer = new XMLSerializer();
  return serializer.serializeToString(svg);
}

/**
 * 2. Generate Clean Static SVG (cleans up internal data attributes)
 */
export function generateCleanSvg(svgRaw: string): string {
  if (typeof window === 'undefined') return svgRaw;
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgRaw, 'image/svg+xml');
  const svg = doc.querySelector('svg');
  if (!svg) return svgRaw;

  // Clean data-mcu-id attributes
  const allNodes = svg.querySelectorAll('*');
  allNodes.forEach((node) => {
    node.removeAttribute('data-mcu-id');
  });

  const serializer = new XMLSerializer();
  return serializer.serializeToString(svg);
}

/**
 * 3. Render a single frame of SVG to an HTML5 Canvas at time t
 */
export async function renderSvgFrameToCanvas(
  svgString: string,
  tracks: AnimationTrack[],
  time: number,
  canvas: HTMLCanvasElement,
  width: number,
  height: number
): Promise<void> {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgString, 'image/svg+xml');
  const svg = doc.querySelector('svg');
  if (!svg) return;

  // Apply computed styles for all elements
  const allNodes = svg.querySelectorAll('[data-mcu-id]');
  allNodes.forEach((node) => {
    const elId = node.getAttribute('data-mcu-id');
    if (elId) {
      const styles = computeElementStylesAtTime(tracks, elId, time);
      applyComputedStylesToElement(node as SVGElement, styles);
    }
  });

  const serializer = new XMLSerializer();
  const frameSvgStr = serializer.serializeToString(svg);
  const blob = new Blob([frameSvgStr], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const img = new Image();
  img.crossOrigin = 'anonymous';

  return new Promise((resolve, reject) => {
    img.onload = () => {
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.clearRect(0, 0, width, height);
        ctx.drawImage(img, 0, 0, width, height);
      }
      URL.revokeObjectURL(url);
      resolve();
    };
    img.onerror = (e) => {
      URL.revokeObjectURL(url);
      reject(e);
    };
    img.src = url;
  });
}

/**
 * 4. Export PNG Sequence via JSZip
 */
export async function exportPngSequenceZip(
  project: ProjectState,
  fps: number = 30,
  scale: number = 1,
  onProgress?: (percent: number, currentFrame: number, totalFrames: number) => void
): Promise<Blob> {
  const { svgRaw, tracks, document: docSettings } = project;
  const duration = docSettings.duration;
  const totalFrames = Math.max(1, Math.round(duration * fps));

  const width = Math.round((docSettings.viewBox.width || 800) * scale);
  const height = Math.round((docSettings.viewBox.height || 600) * scale);

  const canvas = window.document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;

  const zip = new JSZip();
  const folder = zip.folder(`${project.name || 'mcu_motion'}_png_sequence`);

  for (let frame = 0; frame < totalFrames; frame++) {
    const time = (frame / fps);
    await renderSvgFrameToCanvas(svgRaw, tracks, time, canvas, width, height);

    const frameBlob = await new Promise<Blob | null>((resolve) => {
      canvas.toBlob((b) => resolve(b), 'image/png');
    });

    if (frameBlob && folder) {
      const filename = `frame_${String(frame + 1).padStart(4, '0')}.png`;
      folder.file(filename, frameBlob);
    }

    if (onProgress) {
      const pct = Math.round(((frame + 1) / totalFrames) * 100);
      onProgress(pct, frame + 1, totalFrames);
    }
  }

  return await zip.generateAsync({ type: 'blob' });
}

/**
 * 5. Record Video to WebM using HTML5 Canvas & MediaRecorder
 */
export async function recordCanvasVideo(
  project: ProjectState,
  fps: number = 30,
  scale: number = 1,
  onProgress?: (percent: number) => void,
  preferMp4 = false
): Promise<RecordedVideo> {
  const { svgRaw, tracks, document: docSettings } = project;
  const duration = docSettings.duration;
  const totalFrames = Math.max(1, Math.round(duration * fps));

  const width = Math.round((docSettings.viewBox.width || 800) * scale);
  const height = Math.round((docSettings.viewBox.height || 600) * scale);

  const canvas = window.document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;

  if (typeof MediaRecorder === 'undefined' || typeof canvas.captureStream !== 'function') {
    throw new Error('Video export is not supported by this browser. Try a current version of Chrome, Edge, or Safari.');
  }

  const stream = canvas.captureStream(0);
  const videoTrack = stream.getVideoTracks()[0] as CanvasCaptureMediaStreamTrack | undefined;
  if (!videoTrack?.requestFrame) {
    stream.getTracks().forEach((track) => track.stop());
    throw new Error('Frame-accurate video capture is not supported by this browser.');
  }

  const candidateMimeTypes = preferMp4
    ? [
        'video/mp4;codecs=avc1.640028,mp4a.40.2',
        'video/mp4;codecs=avc1.4d4028',
        'video/mp4;codecs=avc1.42E01E,mp4a.40.2',
        'video/mp4',
        'video/webm;codecs=vp9,opus',
        'video/webm;codecs=vp9',
        'video/webm;codecs=vp8',
        'video/webm',
      ]
    : ['video/webm;codecs=vp9', 'video/webm;codecs=vp8', 'video/webm'];
  const mimeType = candidateMimeTypes.find((candidate) => MediaRecorder.isTypeSupported(candidate));
  const videoFormat: RecordedVideo['format'] = mimeType?.startsWith('video/mp4') ? 'mp4' : 'webm';
  const chunks: Blob[] = [];
  let recorder: MediaRecorder | null = null;

  try {
    recorder = new MediaRecorder(stream, {
      ...(mimeType ? { mimeType } : {}),
      videoBitsPerSecond: Math.min(40_000_000, Math.max(5_000_000, width * height * fps * 0.09)),
    });
    recorder.ondataavailable = (event) => {
      if (event.data.size > 0) chunks.push(event.data);
    };
    const stopped = new Promise<Blob>((resolve, reject) => {
      recorder!.onstop = () => {
        const blob = new Blob(chunks, { type: mimeType || recorder!.mimeType || 'video/webm' });
        if (blob.size === 0) reject(new Error('Video export produced an empty file.'));
        else resolve(blob);
      };
      recorder!.onerror = () => reject(new Error('Video recording failed. Try a lower resolution or WebM.'));
    });
    recorder.start(100);

    for (let frame = 0; frame < totalFrames; frame += 1) {
      if (document.visibilityState !== 'visible') {
        throw new Error('Keep the export tab visible until MP4 rendering finishes.');
      }
      await renderSvgFrameToCanvas(svgRaw, tracks, frame / fps, canvas, width, height);
      videoTrack.requestFrame();
      onProgress?.(Math.round(((frame + 1) / totalFrames) * 100));
      await new Promise<void>((resolve) => {
        window.requestAnimationFrame(() => window.setTimeout(resolve, Math.max(0, Math.round(1000 / fps) - 16)));
      });
    }

    if (recorder.state === 'recording') {
      recorder.requestData();
      await new Promise((resolve) => window.setTimeout(resolve, 100));
      recorder.stop();
    }
    return { blob: await stopped, format: videoFormat };
  } finally {
    if (recorder?.state === 'recording') recorder.stop();
    stream.getTracks().forEach((track) => track.stop());
  }
}

async function loadFfmpeg(): Promise<FFmpeg> {
  if (!ffmpegLoadPromise) {
    ffmpegLoadPromise = (async () => {
      const ffmpeg = new FFmpeg();
      const coreUrl = 'https://unpkg.com/@ffmpeg/core@0.12.10/dist/esm';
      await ffmpeg.load({
        coreURL: await toBlobURL(`${coreUrl}/ffmpeg-core.js`, 'text/javascript'),
        wasmURL: await toBlobURL(`${coreUrl}/ffmpeg-core.wasm`, 'application/wasm'),
      });
      ffmpegInstance = ffmpeg;
      return ffmpeg;
    })().catch((error) => {
      ffmpegLoadPromise = null;
      throw error;
    });
  }
  return ffmpegInstance ?? ffmpegLoadPromise;
}

export async function convertVideoToMp4(
  webm: Blob,
  fps: number,
  onProgress?: (percent: number) => void
): Promise<Blob> {
  const ffmpeg = await loadFfmpeg();
  await ffmpeg.deleteFile('input.webm').catch(() => undefined);
  await ffmpeg.deleteFile('output.mp4').catch(() => undefined);
  await ffmpeg.writeFile('input.webm', await fetchFile(webm));
  const reportProgress = ({ progress }: { progress: number }) => {
    onProgress?.(Math.max(0, Math.min(100, Math.round(progress * 100))));
  };
  ffmpeg.on('progress', reportProgress);
  try {
    await ffmpeg.exec([
      '-i', 'input.webm',
      '-an',
      '-c:v', 'libx264',
      '-preset', 'medium',
      '-profile:v', 'high',
      '-r', String(fps),
      '-crf', '18',
      '-pix_fmt', 'yuv420p',
      '-movflags', '+faststart',
      'output.mp4',
    ]);
    const output = await ffmpeg.readFile('output.mp4');
    if (typeof output === 'string') throw new Error('FFmpeg returned invalid MP4 data.');
    const bytes = new Uint8Array(output);
    const buffer = new ArrayBuffer(bytes.byteLength);
    new Uint8Array(buffer).set(bytes);
    return new Blob([buffer], { type: 'video/mp4' });
  } finally {
    ffmpeg.off('progress', reportProgress);
    await ffmpeg.deleteFile('input.webm').catch(() => undefined);
    await ffmpeg.deleteFile('output.mp4').catch(() => undefined);
  }
}

/**
 * Helper to trigger browser file download
 */
export function downloadFile(blob: Blob | string, filename: string, mimeType: string = 'text/plain') {
  const blobObj = typeof blob === 'string' ? new Blob([blob], { type: mimeType }) : blob;
  const url = URL.createObjectURL(blobObj);
  const a = window.document.createElement('a');
  a.href = url;
  a.download = filename;
  window.document.body.appendChild(a);
  a.click();
  window.document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
