import JSZip from 'jszip';
import { ProjectState, AnimationTrack, Keyframe, SvgElementNode } from './types';
import { flattenElementTree } from './svgParser';
import { computeElementStylesAtTime, applyComputedStylesToElement } from './animationEngine';

/**
 * 1. Generate Standalone Animated SVG with embedded CSS Keyframes
 */
export function generateAnimatedSvg(project: ProjectState): string {
  const { svgRaw, tracks, document: docSettings } = project;
  const { duration, loop, viewBox } = docSettings;

  if (typeof window === 'undefined') return svgRaw;

  const parser = new DOMParser();
  const doc = parser.parseFromString(svgRaw, 'image/svg+xml');
  const svg = doc.querySelector('svg');
  if (!svg) return svgRaw;

  // Group tracks by elementId
  const tracksByElement = new Map<string, AnimationTrack[]>();
  for (const t of tracks) {
    if (!tracksByElement.has(t.elementId)) {
      tracksByElement.set(t.elementId, []);
    }
    tracksByElement.get(t.elementId)!.push(t);
  }

  let cssRules = `
    /* Generated by MCU SVG Motion Studio */
    svg { overflow: visible; }
  `;

  tracksByElement.forEach((elemTracks, elementId) => {
    const el = svg.querySelector(`[data-mcu-id="${elementId}"]`);
    if (!el) return;

    // Collect all unique timestamps
    const timestamps = new Set<number>([0, duration]);
    elemTracks.forEach((tr) => {
      tr.keyframes.forEach((kf) => timestamps.add(Math.max(0, Math.min(duration, kf.time))));
    });

    const sortedTimes = Array.from(timestamps).sort((a, b) => a - b);
    const keyframesName = `anim_${elementId.replace(/[^a-zA-Z0-9_]/g, '_')}`;

    let keyframesCss = `@keyframes ${keyframesName} {\n`;

    sortedTimes.forEach((t) => {
      const pct = Math.round((t / duration) * 1000) / 10;
      const styles = computeElementStylesAtTime(elemTracks, elementId, t);

      const transform = `translate(${styles.x}px, ${styles.y}px) rotate(${styles.rotation}deg) scale(${styles.scaleX / 100}, ${styles.scaleY / 100}) skewX(${styles.skewX}deg) skewY(${styles.skewY}deg)`;
      const opacity = Math.max(0, Math.min(1, styles.opacity / 100));

      keyframesCss += `  ${pct}% {\n`;
      keyframesCss += `    transform: ${transform};\n`;
      keyframesCss += `    transform-origin: ${styles.originX}% ${styles.originY}%;\n`;
      keyframesCss += `    opacity: ${opacity};\n`;
      if (styles.strokeDashoffset !== undefined) {
        keyframesCss += `    stroke-dashoffset: ${styles.strokeDashoffset};\n`;
      }
      keyframesCss += `  }\n`;
    });

    keyframesCss += `}\n`;

    cssRules += keyframesCss;
    cssRules += `
      [data-mcu-id="${elementId}"] {
        animation: ${keyframesName} ${duration}s ${loop ? 'infinite' : 'forwards'} linear;
        transform-box: fill-box;
      }\n`;
  });

  // Inject <style> into <defs> or <svg>
  let defs = svg.querySelector('defs');
  if (!defs) {
    defs = doc.createElementNS('http://www.w3.org/2000/svg', 'defs');
    svg.insertBefore(defs, svg.firstChild);
  }

  const styleEl = doc.createElementNS('http://www.w3.org/2000/svg', 'style');
  styleEl.setAttribute('type', 'text/css');
  styleEl.textContent = cssRules;
  defs.appendChild(styleEl);

  const serializer = new XMLSerializer();
  return serializer.serializeToString(svg);
}

/**
 * 2. Generate Clean Static SVG (cleans up internal data attributes)
 */
export function generateCleanSvg(svgRaw: string): string {
  if (typeof window === 'undefined') return svgRaw;
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgRaw, 'image/svg+xml');
  const svg = doc.querySelector('svg');
  if (!svg) return svgRaw;

  // Clean data-mcu-id attributes
  const allNodes = svg.querySelectorAll('*');
  allNodes.forEach((node) => {
    node.removeAttribute('data-mcu-id');
  });

  const serializer = new XMLSerializer();
  return serializer.serializeToString(svg);
}

/**
 * 3. Render a single frame of SVG to an HTML5 Canvas at time t
 */
export async function renderSvgFrameToCanvas(
  svgString: string,
  tracks: AnimationTrack[],
  time: number,
  canvas: HTMLCanvasElement,
  width: number,
  height: number
): Promise<void> {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgString, 'image/svg+xml');
  const svg = doc.querySelector('svg');
  if (!svg) return;

  // Apply computed styles for all elements
  const allNodes = svg.querySelectorAll('[data-mcu-id]');
  allNodes.forEach((node) => {
    const elId = node.getAttribute('data-mcu-id');
    if (elId) {
      const styles = computeElementStylesAtTime(tracks, elId, time);
      applyComputedStylesToElement(node as SVGElement, styles);
    }
  });

  const serializer = new XMLSerializer();
  const frameSvgStr = serializer.serializeToString(svg);
  const blob = new Blob([frameSvgStr], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const img = new Image();
  img.crossOrigin = 'anonymous';

  return new Promise((resolve, reject) => {
    img.onload = () => {
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.clearRect(0, 0, width, height);
        ctx.drawImage(img, 0, 0, width, height);
      }
      URL.revokeObjectURL(url);
      resolve();
    };
    img.onerror = (e) => {
      URL.revokeObjectURL(url);
      reject(e);
    };
    img.src = url;
  });
}

/**
 * 4. Export PNG Sequence via JSZip
 */
export async function exportPngSequenceZip(
  project: ProjectState,
  fps: number = 30,
  scale: number = 1,
  onProgress?: (percent: number, currentFrame: number, totalFrames: number) => void
): Promise<Blob> {
  const { svgRaw, tracks, document: docSettings } = project;
  const duration = docSettings.duration;
  const totalFrames = Math.max(1, Math.round(duration * fps));

  const width = Math.round((docSettings.viewBox.width || 800) * scale);
  const height = Math.round((docSettings.viewBox.height || 600) * scale);

  const canvas = window.document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;

  const zip = new JSZip();
  const folder = zip.folder(`${project.name || 'mcu_motion'}_png_sequence`);

  for (let frame = 0; frame < totalFrames; frame++) {
    const time = (frame / fps);
    await renderSvgFrameToCanvas(svgRaw, tracks, time, canvas, width, height);

    const frameBlob = await new Promise<Blob | null>((resolve) => {
      canvas.toBlob((b) => resolve(b), 'image/png');
    });

    if (frameBlob && folder) {
      const filename = `frame_${String(frame + 1).padStart(4, '0')}.png`;
      folder.file(filename, frameBlob);
    }

    if (onProgress) {
      const pct = Math.round(((frame + 1) / totalFrames) * 100);
      onProgress(pct, frame + 1, totalFrames);
    }
  }

  return await zip.generateAsync({ type: 'blob' });
}

/**
 * 5. Record Video to WebM using HTML5 Canvas & MediaRecorder
 */
export async function recordWebmVideo(
  project: ProjectState,
  fps: number = 30,
  scale: number = 1,
  onProgress?: (percent: number) => void
): Promise<Blob> {
  const { svgRaw, tracks, document: docSettings } = project;
  const duration = docSettings.duration;
  const totalFrames = Math.max(1, Math.round(duration * fps));

  const width = Math.round((docSettings.viewBox.width || 800) * scale);
  const height = Math.round((docSettings.viewBox.height || 600) * scale);

  const canvas = window.document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;

  const stream = canvas.captureStream(fps);
  const chunks: Blob[] = [];

  const mimeType = MediaRecorder.isTypeSupported('video/webm;codecs=vp9')
    ? 'video/webm;codecs=vp9'
    : MediaRecorder.isTypeSupported('video/webm')
    ? 'video/webm'
    : '';

  const recorder = new MediaRecorder(stream, mimeType ? { mimeType } : undefined);

  recorder.ondataavailable = (e) => {
    if (e.data && e.data.size > 0) {
      chunks.push(e.data);
    }
  };

  recorder.start();

  for (let frame = 0; frame < totalFrames; frame++) {
    const time = (frame / fps);
    await renderSvgFrameToCanvas(svgRaw, tracks, time, canvas, width, height);
    if (onProgress) {
      onProgress(Math.round(((frame + 1) / totalFrames) * 100));
    }
    // Small yield to allow MediaRecorder to process canvas frame
    await new Promise((r) => setTimeout(r, 1000 / fps));
  }

  recorder.stop();

  return new Promise((resolve) => {
    recorder.onstop = () => {
      const videoBlob = new Blob(chunks, { type: 'video/webm' });
      resolve(videoBlob);
    };
  });
}

/**
 * Helper to trigger browser file download
 */
export function downloadFile(blob: Blob | string, filename: string, mimeType: string = 'text/plain') {
  const blobObj = typeof blob === 'string' ? new Blob([blob], { type: mimeType }) : blob;
  const url = URL.createObjectURL(blobObj);
  const a = window.document.createElement('a');
  a.href = url;
  a.download = filename;
  window.document.body.appendChild(a);
  a.click();
  window.document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
